# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8aadb131f2f471f7e281c9ce67af6bacadbffc10eb4bdd15e8cb44dcac4dd39d85afdd09eb68f0f26ca2fc8056c972be478580186760bcc159509318581585c5

test:
  secret_key_base: 9af89f1503f05856af10cad11ee0b3b69ad368ff75e2d275121b3977bcead5c3ebb7c83fb267b6e39ddc8cea9a1677854e1a6ef651807c47682a3309a8c4f7ca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
